server:
  port: 8899
  address: 192.168.11.110
#jdbc:mysql://localhost:3306/test01
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test01
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml  #对应mapper映射xml文件所在路径
  type-aliases-package: com.example.model;  #对应实体类路径
line:
  bot:
    channel-token: 9hL3wBPAAhzX8LpiE42a4O2u3XLGI1/gkcHFoYUSgtIL4x4Z1tWe6YxGrcynVhLRFkc6T74hon98f1JpPHD6LldEfH1loowTEZZfNZOU4LGlQT74aQAU1ah/oCO3q2w+CoAO2eCLqdNvjmhcwHBHfAdB04t89/1O/w1cDnyilFU=
    channel-secret: 003a9f5bdcf4e4bfda26b20fd9e56b10


